[package]
name = "byewlma"
version = "0.1.0"
authors = ["Elliott Clarke <ecclarke42@gmail.com>"]
edition = "2018"

[workspace]
members = [
    ".tools"
]

exclude = [
    "examples/*"
]

[dependencies]
yew = { git = "https://github.com/yewstack/yew/" }
strum = { version = "0.21", features = ["derive"] }