[package]
name = "byewlma"
version = "0.1.0"
authors = ["Elliott Clarke <ecclarke42@gmail.com>"]
edition = "2018"

exclude = [
    ".tools",
    "examples/*"
]

[workspace]
members = [
    ".tools",
    "examples/*"
]


[dependencies]
paste = "*"
strum = { version = "0.21", features = ["derive"] }
yew = { git = "https://github.com/yewstack/yew/" }
yewtil = { git = "https://github.com/yewstack/yew/", features = ["pure"] }